PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
SELECT ?personName ?activityTitle
WHERE {?person a rico:Person ;
        rico:name ?personName ;
        rico:performsOrPerformed ?activity .
      ?activity rico:name ?activityTitle .}
