PREFIX rico:<https://www.ica.org/standards/RiC/ontology#> SELECT ?IDdokumenta ?nestandardniOblikDatuma WHERE {?RecordSet a rico:RecordSet; rico:identifier ?IDdokumenta; rico:isAssociatedWithDate/rico:expressedDate ?nestandardniOblikDatuma.}